platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/dvlproad/dvlproadSpecs'

inhibit_all_warnings!

post_install do |installer|
   
   puts 'Determining pod project minimal deployment target'
   
   pods_project = installer.pods_project
   deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
   deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
   minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
   
   puts 'Minimal deployment target is ' + minimal_deployment_target
   puts 'Setting each pod deployment target to ' + minimal_deployment_target
   
   installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
           config.build_settings[deployment_target_key] = minimal_deployment_target
       end
   end
end

target 'CJViewModelDemo' do
  pod 'CJBaseUtil',          :subspecs => ['CJDataUtil']
#   pod 'CJDemoCommon'
  pod 'CQThemeBaseUIKit'
  pod 'CQOverlayKit'
  pod 'CJBaseUIKit', :subspecs => ['UIColor', 'UINavigationBar']
  pod 'CQDemoKit',            '~> 0.4.0', :subspecs => ['Home_Base']
  pod 'CJDemoService/User'
  pod 'CJDemoModuleLogin/Logic/NDM'
   
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'KVOController', '~> 1.2.0'

  pod 'IQKeyboardManager'
end

target 'CJViewModelDemoTests' do
   
end
